version: '3.0'

services:
  audacious_minecraft:
    image: audacious_minecraft:latest
    restart: always
    volumes:
      - audacious_minecraft:/audacious_minecraft/server/

    ports:
      - '25565:25565'
      - '25575:25575'

# Names our volume
volumes:
  audacious_minecraft:
